# Listar Todos
GET http://localhost:8080/api/task
# Authorization: Basic user ea212276-1d9c-4bc9-898e-b67aa29ef0b1
###

# Detalhes
GET http://localhost:8080/api/task/1

###

# Apagar
DELETE  http://localhost:8080/api/task/1

###

# Cadastrar
POST  http://localhost:8080/api/task
Content-Type: application/json
Authorization: Basic joao@fiap.com.br 123

{
  "title": "Modelar o BD",
  "description": "Modelar as tabelas do banco de dados",
  "score": 100
}